version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./app/server/Dockerfile
  naming_service:
    build:
      context: .
      dockerfile: ./app/naming_service/Dockerfile
  client:
    build:
      context: .
      dockerfile: ./app/client/Dockerfile